// request recommend list
export const FETCH_RECOMMEND_SOUNDS = {
  START: 'FETCH_RECOMMEND_SONDS_START',
  SUCCESS: 'FETCH_RECOMMEND_SONDS_SUCCESS',
  ERROR: 'FETCH_RECOMMEND_SONDS_ERROR'
};
export type FETCH_RECOMMEND_SOUNDS_START = typeof FETCH_RECOMMEND_SOUNDS.START;
export type FETCH_RECOMMEND_SOUNDS_SUCCESS = typeof FETCH_RECOMMEND_SOUNDS.SUCCESS;
export type FETCH_RECOMMEND_SOUNDS_ERROR = typeof FETCH_RECOMMEND_SOUNDS.ERROR;



export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;
